2025-04-28 12:02:23,065 - INFO - [<module>] - Logging configured. Log file: Selenium-Logs\app_20250428_120223.log
2025-04-28 12:02:23,065 - INFO - [<module>] - Configuration loaded.
2025-04-28 12:02:23,065 - INFO - [<module>] - Utility functions defined.
2025-04-28 12:02:23,067 - INFO - [<module>] - Flask application initialized.
2025-04-28 12:02:23,067 - INFO - [<module>] - Global state variables initialized.
2025-04-28 12:02:23,121 - INFO - [<module>] - Async Telegram API functions defined.
2025-04-28 12:02:23,795 - INFO - [<module>] - Flask async routes defined.
2025-04-28 12:02:23,797 - INFO - [info] - Running on http://0.0.0.0:5000 (CTRL + C to quit)
2025-04-28 12:02:29,681 - INFO - [index] - Serving index page.
2025-04-28 12:02:29,952 - INFO - [index] - Serving index page.
2025-04-28 12:02:40,300 - INFO - [initiate_upload] - Received request to initiate upload.
2025-04-28 12:02:40,305 - INFO - [initiate_upload] - [d6f899fc-777b-4c27-9671-23892290ec56] Saving temporary file for 'index.html' to 'uploads_temp\d6f899fc-777b-4c27-9671-23892290ec56_upload.tmp'
2025-04-28 12:02:40,311 - INFO - [initiate_upload] - [d6f899fc-777b-4c27-9671-23892290ec56] Temporary file saved successfully for 'index.html'.
2025-04-28 12:02:40,322 - INFO - [stream_progress] - SSE connection request for upload_id: d6f899fc-777b-4c27-9671-23892290ec56
2025-04-28 12:02:40,331 - ERROR - [exception] - Error in ASGI Framework
Traceback (most recent call last):
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\hypercorn\asyncio\task_group.py", line 27, in _handle
    await app(scope, receive, send, sync_spawn, call_soon)
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\hypercorn\app_wrappers.py", line 51, in __call__
    await self.handle_http(scope, receive, send, sync_spawn, call_soon)
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\hypercorn\app_wrappers.py", line 83, in handle_http
    await sync_spawn(self.run_app, environ, partial(call_soon, send))
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\hypercorn\app_wrappers.py", line 113, in run_app
    for output in response_body:
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\werkzeug\wsgi.py", line 256, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\werkzeug\wrappers\response.py", line 32, in _iter_encoded
    for item in iterable:
TypeError: 'function' object is not iterable
2025-04-28 12:03:36,995 - INFO - [initiate_upload] - Received request to initiate upload.
2025-04-28 12:03:36,997 - INFO - [initiate_upload] - [4e595b0b-8987-496f-af2d-fede40b0d4a7] Saving temporary file for 'index.html' to 'uploads_temp\4e595b0b-8987-496f-af2d-fede40b0d4a7_upload.tmp'
2025-04-28 12:03:36,999 - INFO - [initiate_upload] - [4e595b0b-8987-496f-af2d-fede40b0d4a7] Temporary file saved successfully for 'index.html'.
2025-04-28 12:03:37,005 - INFO - [stream_progress] - SSE connection request for upload_id: 4e595b0b-8987-496f-af2d-fede40b0d4a7
2025-04-28 12:03:37,007 - ERROR - [exception] - Error in ASGI Framework
Traceback (most recent call last):
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\hypercorn\asyncio\task_group.py", line 27, in _handle
    await app(scope, receive, send, sync_spawn, call_soon)
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\hypercorn\app_wrappers.py", line 51, in __call__
    await self.handle_http(scope, receive, send, sync_spawn, call_soon)
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\hypercorn\app_wrappers.py", line 83, in handle_http
    await sync_spawn(self.run_app, environ, partial(call_soon, send))
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\hypercorn\app_wrappers.py", line 113, in run_app
    for output in response_body:
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\werkzeug\wsgi.py", line 256, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\werkzeug\wrappers\response.py", line 32, in _iter_encoded
    for item in iterable:
TypeError: 'function' object is not iterable
2025-04-28 12:03:40,614 - INFO - [list_user_files] - Async request received to list files for user: 'Grecy'
2025-04-28 12:03:40,617 - INFO - [load_metadata_sync] - Successfully loaded metadata from 'metadata.json'.
2025-04-28 12:03:40,617 - INFO - [list_user_files] - Found 5 file records for user 'Grecy'.
2025-04-28 12:03:42,304 - INFO - [prepare_download_stream] - [c4aecce6-5175-40fa-98c5-95d11f0fe2f3] SSE connection request for download prep: User='Grecy', File='tsetup-x64.5.12.3.exe'
2025-04-28 12:03:42,306 - ERROR - [exception] - Error in ASGI Framework
Traceback (most recent call last):
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\hypercorn\asyncio\task_group.py", line 27, in _handle
    await app(scope, receive, send, sync_spawn, call_soon)
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\hypercorn\app_wrappers.py", line 51, in __call__
    await self.handle_http(scope, receive, send, sync_spawn, call_soon)
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\hypercorn\app_wrappers.py", line 83, in handle_http
    await sync_spawn(self.run_app, environ, partial(call_soon, send))
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\hypercorn\app_wrappers.py", line 113, in run_app
    for output in response_body:
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\werkzeug\wsgi.py", line 256, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\werkzeug\wrappers\response.py", line 32, in _iter_encoded
    for item in iterable:
TypeError: 'function' object is not iterable
2025-04-28 12:03:43,303 - INFO - [prepare_download_stream] - [ba529d2d-18b3-4b62-8c99-d75ce7c5cdef] SSE connection request for download prep: User='Grecy', File='tsetup-x64.5.12.3.exe'
2025-04-28 12:03:43,306 - ERROR - [exception] - Error in ASGI Framework
Traceback (most recent call last):
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\hypercorn\asyncio\task_group.py", line 27, in _handle
    await app(scope, receive, send, sync_spawn, call_soon)
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\hypercorn\app_wrappers.py", line 51, in __call__
    await self.handle_http(scope, receive, send, sync_spawn, call_soon)
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\hypercorn\app_wrappers.py", line 83, in handle_http
    await sync_spawn(self.run_app, environ, partial(call_soon, send))
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\hypercorn\app_wrappers.py", line 113, in run_app
    for output in response_body:
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\werkzeug\wsgi.py", line 256, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\werkzeug\wrappers\response.py", line 32, in _iter_encoded
    for item in iterable:
TypeError: 'function' object is not iterable
2025-04-28 12:03:45,376 - INFO - [delete_file_record] - Async DELETE request for user='Grecy', file='tsetup-x64.5.12.3.exe'
2025-04-28 12:03:45,379 - INFO - [load_metadata_sync] - Successfully loaded metadata from 'metadata.json'.
2025-04-28 12:03:45,380 - INFO - [delete_file_record] - Removed record for 'tsetup-x64.5.12.3.exe' for user 'Grecy'.
2025-04-28 12:03:45,407 - INFO - [save_metadata_sync] - Successfully saved metadata to 'metadata.json'.
2025-04-28 12:03:45,409 - INFO - [delete_file_record] - Successfully saved metadata after deleting 'tsetup-x64.5.12.3.exe'.
2025-04-28 12:03:48,114 - INFO - [prepare_download_stream] - [4e2d9978-8044-4e3f-b6fa-b7549ecf1a11] SSE connection request for download prep: User='Grecy', File='download_page.html'
2025-04-28 12:03:48,118 - ERROR - [exception] - Error in ASGI Framework
Traceback (most recent call last):
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\hypercorn\asyncio\task_group.py", line 27, in _handle
    await app(scope, receive, send, sync_spawn, call_soon)
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\hypercorn\app_wrappers.py", line 51, in __call__
    await self.handle_http(scope, receive, send, sync_spawn, call_soon)
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\hypercorn\app_wrappers.py", line 83, in handle_http
    await sync_spawn(self.run_app, environ, partial(call_soon, send))
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\hypercorn\app_wrappers.py", line 113, in run_app
    for output in response_body:
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\werkzeug\wsgi.py", line 256, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\werkzeug\wrappers\response.py", line 32, in _iter_encoded
    for item in iterable:
TypeError: 'function' object is not iterable
2025-04-28 12:03:49,008 - INFO - [prepare_download_stream] - [a5705ac1-12e1-4f43-a9b3-854ef56d98d6] SSE connection request for download prep: User='Grecy', File='download_page.html'
2025-04-28 12:03:49,010 - ERROR - [exception] - Error in ASGI Framework
Traceback (most recent call last):
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\hypercorn\asyncio\task_group.py", line 27, in _handle
    await app(scope, receive, send, sync_spawn, call_soon)
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\hypercorn\app_wrappers.py", line 51, in __call__
    await self.handle_http(scope, receive, send, sync_spawn, call_soon)
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\hypercorn\app_wrappers.py", line 83, in handle_http
    await sync_spawn(self.run_app, environ, partial(call_soon, send))
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\hypercorn\app_wrappers.py", line 113, in run_app
    for output in response_body:
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\werkzeug\wsgi.py", line 256, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\werkzeug\wrappers\response.py", line 32, in _iter_encoded
    for item in iterable:
TypeError: 'function' object is not iterable
2025-04-28 12:03:49,704 - INFO - [prepare_download_stream] - [3225ae79-1cd3-4e8b-adf1-916047e46ec2] SSE connection request for download prep: User='Grecy', File='download_page.html'
2025-04-28 12:03:49,707 - ERROR - [exception] - Error in ASGI Framework
Traceback (most recent call last):
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\hypercorn\asyncio\task_group.py", line 27, in _handle
    await app(scope, receive, send, sync_spawn, call_soon)
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\hypercorn\app_wrappers.py", line 51, in __call__
    await self.handle_http(scope, receive, send, sync_spawn, call_soon)
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\hypercorn\app_wrappers.py", line 83, in handle_http
    await sync_spawn(self.run_app, environ, partial(call_soon, send))
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\hypercorn\app_wrappers.py", line 113, in run_app
    for output in response_body:
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\werkzeug\wsgi.py", line 256, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\werkzeug\wrappers\response.py", line 32, in _iter_encoded
    for item in iterable:
TypeError: 'function' object is not iterable
2025-04-28 12:03:50,794 - INFO - [prepare_download_stream] - [b6b505e4-230b-45ad-89ee-e8dcc91befae] SSE connection request for download prep: User='Grecy', File='download_page.html'
2025-04-28 12:03:50,798 - ERROR - [exception] - Error in ASGI Framework
Traceback (most recent call last):
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\hypercorn\asyncio\task_group.py", line 27, in _handle
    await app(scope, receive, send, sync_spawn, call_soon)
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\hypercorn\app_wrappers.py", line 51, in __call__
    await self.handle_http(scope, receive, send, sync_spawn, call_soon)
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\hypercorn\app_wrappers.py", line 83, in handle_http
    await sync_spawn(self.run_app, environ, partial(call_soon, send))
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\hypercorn\app_wrappers.py", line 113, in run_app
    for output in response_body:
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\werkzeug\wsgi.py", line 256, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\werkzeug\wrappers\response.py", line 32, in _iter_encoded
    for item in iterable:
TypeError: 'function' object is not iterable
2025-04-28 12:03:52,412 - INFO - [delete_file_record] - Async DELETE request for user='Grecy', file='download_page.html'
2025-04-28 12:03:52,426 - INFO - [load_metadata_sync] - Successfully loaded metadata from 'metadata.json'.
2025-04-28 12:03:52,427 - INFO - [delete_file_record] - Removed record for 'download_page.html' for user 'Grecy'.
2025-04-28 12:03:52,440 - INFO - [save_metadata_sync] - Successfully saved metadata to 'metadata.json'.
2025-04-28 12:03:52,440 - INFO - [delete_file_record] - Successfully saved metadata after deleting 'download_page.html'.
2025-04-28 12:03:54,629 - INFO - [delete_file_record] - Async DELETE request for user='Grecy', file='vfcompat.dll'
2025-04-28 12:03:54,646 - INFO - [load_metadata_sync] - Successfully loaded metadata from 'metadata.json'.
2025-04-28 12:03:54,647 - INFO - [delete_file_record] - Removed record for 'vfcompat.dll' for user 'Grecy'.
2025-04-28 12:03:54,661 - INFO - [save_metadata_sync] - Successfully saved metadata to 'metadata.json'.
2025-04-28 12:03:54,661 - INFO - [delete_file_record] - Successfully saved metadata after deleting 'vfcompat.dll'.
2025-04-28 12:03:56,142 - INFO - [delete_file_record] - Async DELETE request for user='Grecy', file='500MB-CZIPtestfile.org (1).zip'
2025-04-28 12:03:56,160 - INFO - [load_metadata_sync] - Successfully loaded metadata from 'metadata.json'.
2025-04-28 12:03:56,162 - INFO - [delete_file_record] - Removed record for '500MB-CZIPtestfile.org (1).zip' for user 'Grecy'.
2025-04-28 12:03:56,170 - INFO - [save_metadata_sync] - Successfully saved metadata to 'metadata.json'.
2025-04-28 12:03:56,171 - INFO - [delete_file_record] - Successfully saved metadata after deleting '500MB-CZIPtestfile.org (1).zip'.
2025-04-28 12:03:57,884 - INFO - [delete_file_record] - Async DELETE request for user='Grecy', file='comment.txt'
2025-04-28 12:03:57,902 - INFO - [load_metadata_sync] - Successfully loaded metadata from 'metadata.json'.
2025-04-28 12:03:57,904 - INFO - [delete_file_record] - Removed record for 'comment.txt' for user 'Grecy'.
2025-04-28 12:03:57,904 - INFO - [delete_file_record] - Removing empty user entry for 'Grecy'.
2025-04-28 12:03:57,911 - INFO - [save_metadata_sync] - Successfully saved metadata to 'metadata.json'.
2025-04-28 12:03:57,912 - INFO - [delete_file_record] - Successfully saved metadata after deleting 'comment.txt'.
2025-04-28 12:04:05,730 - INFO - [initiate_upload] - Received request to initiate upload.
2025-04-28 12:04:05,731 - INFO - [initiate_upload] - [fdb59385-83ba-4ba1-bee7-fa2870856a46] Saving temporary file for 'index.html' to 'uploads_temp\fdb59385-83ba-4ba1-bee7-fa2870856a46_upload.tmp'
2025-04-28 12:04:05,733 - INFO - [initiate_upload] - [fdb59385-83ba-4ba1-bee7-fa2870856a46] Temporary file saved successfully for 'index.html'.
2025-04-28 12:04:05,738 - INFO - [stream_progress] - SSE connection request for upload_id: fdb59385-83ba-4ba1-bee7-fa2870856a46
2025-04-28 12:04:05,741 - ERROR - [exception] - Error in ASGI Framework
Traceback (most recent call last):
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\hypercorn\asyncio\task_group.py", line 27, in _handle
    await app(scope, receive, send, sync_spawn, call_soon)
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\hypercorn\app_wrappers.py", line 51, in __call__
    await self.handle_http(scope, receive, send, sync_spawn, call_soon)
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\hypercorn\app_wrappers.py", line 83, in handle_http
    await sync_spawn(self.run_app, environ, partial(call_soon, send))
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\hypercorn\app_wrappers.py", line 113, in run_app
    for output in response_body:
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\werkzeug\wsgi.py", line 256, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\werkzeug\wrappers\response.py", line 32, in _iter_encoded
    for item in iterable:
TypeError: 'function' object is not iterable
