2025-04-28 12:18:01,105 - INFO - [<module>] - Logging configured. Log file: Selenium-Logs\app_20250428_121801.log
2025-04-28 12:18:01,106 - INFO - [<module>] - Configuration loaded.
2025-04-28 12:18:01,106 - INFO - [<module>] - Utility functions defined.
2025-04-28 12:18:01,107 - INFO - [<module>] - Flask application initialized.
2025-04-28 12:18:01,108 - INFO - [<module>] - Global state variables initialized.
2025-04-28 12:18:01,194 - INFO - [<module>] - Async Telegram API functions defined.
2025-04-28 12:18:01,651 - INFO - [<module>] - Flask async routes defined.
2025-04-28 12:18:01,654 - INFO - [info] - Running on http://0.0.0.0:5000 (CTRL + C to quit)
2025-04-28 12:18:13,196 - INFO - [index] - Serving index page.
2025-04-28 12:18:22,249 - INFO - [index] - Serving index page.
2025-04-28 12:18:28,058 - INFO - [initiate_upload] - Received request to initiate upload.
2025-04-28 12:18:28,062 - INFO - [initiate_upload] - [4bfd87b2-f22e-4a95-a77b-9de371f46eaf] Saving temporary file for '.gitattributes' to 'uploads_temp\4bfd87b2-f22e-4a95-a77b-9de371f46eaf_upload.tmp'
2025-04-28 12:18:28,067 - INFO - [initiate_upload] - [4bfd87b2-f22e-4a95-a77b-9de371f46eaf] Temporary file saved successfully for '.gitattributes'.
2025-04-28 12:18:28,087 - INFO - [stream_progress] - SSE connection request for upload_id: 4bfd87b2-f22e-4a95-a77b-9de371f46eaf
2025-04-28 12:18:28,089 - ERROR - [exception] - Error in ASGI Framework
Traceback (most recent call last):
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\hypercorn\asyncio\task_group.py", line 27, in _handle
    await app(scope, receive, send, sync_spawn, call_soon)
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\hypercorn\app_wrappers.py", line 51, in __call__
    await self.handle_http(scope, receive, send, sync_spawn, call_soon)
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\hypercorn\app_wrappers.py", line 83, in handle_http
    await sync_spawn(self.run_app, environ, partial(call_soon, send))
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\hypercorn\app_wrappers.py", line 113, in run_app
    for output in response_body:
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\werkzeug\wsgi.py", line 256, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "e:\Telegram_tool\Telegram_Bot_Tool\.venv\Lib\site-packages\werkzeug\wrappers\response.py", line 32, in _iter_encoded
    for item in iterable:
TypeError: 'async_generator' object is not iterable
